fs = require 'fs'
_ = require 'underscore'
_s = require 'underscore.string'
wordnet = require 'wordnet'
poss = {}
wordCandidates = []
process.chdir('../data')

mark = (word, pos)=>
  if poss[pos]?
    poss[pos].push word
  else 
    poss[pos] = [word]

mark 'so', 'conjunction'

fs.readFile  'common2LetterWordCandidates.json', 'utf8', (error, data2)=>
  wordCandidates = wordCandidates.concat JSON.parse(data2)
  wordCandidates = wordCandidates.concat ['I']
  console.log '2 Letter Word Candidates: ',wordCandidates.length
  fs.readFile  'common3LetterWordCandidates.json', 'utf8', (error, data3)=>
    wordCandidates = wordCandidates.concat JSON.parse(data3)
    console.log '3 Letter Word Candidates: ',wordCandidates.length
    fs.readFile  'common4LetterWordCandidates.json', 'utf8', (error, data4)=>
      wordCandidates = wordCandidates.concat JSON.parse(data4)
      console.log '4 Letter Word Candidates: ',wordCandidates.length
      fs.readFile  'common5LetterWordCandidates.json', 'utf8', (error, data5)=>
        wordCandidates = wordCandidates.concat JSON.parse(data5)
        console.log '5 Letter Word Candidates: ',wordCandidates.length
        fs.readFile  'common6LetterWordCandidates.json', 'utf8', (error, data6)=>
          wordCandidates = wordCandidates.concat JSON.parse(data6)
          console.log '6 Letter Word Candidates: ',wordCandidates.length

          # wordCandidates = _.shuffle wordCandidates
          pos = {}
          # shortText = wordCandidates[0..99].join ' '
          _.each wordCandidates, (word)=>
            wordnet.lookup word, (err, definitions)=>
              if err 
                if word is 'I'
                  mark word, 'pronoun'
                  mark 'he', 'pronoun'
                if word is 'is'
                  mark word, 'verb'
                else if word is 'solos'
                  mark word, 'presentVerb'
                else if word is 'sighs'
                  mark word, 'presentVerb'
                else if word is 'shh'
                  mark word, 'interjection'
                else if word is 'she'
                  mark word, 'pronoun'
                else if word is 'his'
                  mark word, 'possessivePronoun'
                else if word is 'sighs'
                  mark word, 'presentVerb'
                else if word is 'sighs'
                  mark word, 'presentVerb'
                else if word is 'goes'
                  mark word, 'presentVerb'
                else if word is 'soils'
                  mark word, 'presentVerb'
                else if word is 'slogs'
                  mark word, 'presentVerb'
                else if word is 'shies'
                  mark word, 'presentVerb'
                else if word is 'sells'
                  mark word, 'presentVerb'
                else if word is 'ogles'
                  mark word, 'presentVerb'
                else if word is 'lobos'
                  mark word, 'noun'
                else if word is 'booboo'
                  mark word, 'noun'
                else if word is 'beebee'
                  mark word, 'noun'
                  mark word, 'adjective'
                else if word is 'boohoo'
                  mark word, 'noun'
                else if word is 'loses'
                  mark word, 'presentVerb'
                else if word is 'oboes'
                  mark word, 'pluralNoun'
                else if word is 'hills'
                  mark word, 'pluralNoun'
                else if word is 'else'
                  mark word, 'adverb'
                else if word is 'hills'
                  mark word, 'pluralNoun'
                else if word is 'hills'
                  mark word, 'pluralNoun'
                else if word is 'hills'
                  mark word, 'pluralNoun'
                else if word is 'hills'
                  mark word, 'pluralNoun'
                else if word is 'oils'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else if word is 'gills'
                  mark word, 'pluralNoun'
                else if word is 'holes'
                  mark word, 'pluralNoun'
                else if word is 'bolos'
                  mark word, 'pluralNoun'
                else if word is 'looses'
                  mark word, 'presentVerb'
                else if word is 'sobs'
                  mark word, 'presentVerb'
                else if word is 'isles'
                  mark word, 'pluralNoun'
                else if word is 'highs'
                  mark word, 'pluralNoun'
                else if word is 'heels'
                  mark word, 'pluralNoun'
                else if word is 'bills'
                  mark word, 'pluralNoun'
                else if word is 'bells'
                  mark word, 'pluralNoun'
                else if word is 'hisses'
                  mark word, 'verb'
                  mark word, 'presentVerb'
                else if word is 'gooses'
                  mark word, 'verb'
                else if word is 'lo'
                  mark word, 'interjection'
                else if word is 'blooie'
                  mark word, 'adjective'
                else if word is 'shells'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else if word is 'bosses'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else if word is 'globes'
                  mark word, 'pluralNoun'
                else if word is 'igloos'
                  mark word, 'pluralNoun'
                else if word is 'ibises'
                  mark word, 'pluralNoun'
                else if word is 'lilies'
                  mark word, 'pluralNoun'
                else if word is 'hoboes'
                  mark word, 'pluralNoun'
                else if word is 'lies'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else if word is 'hogs'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else if word is 'did'
                  mark word, 'pastVerb'
                else if word is 'hid'
                  mark word, 'pastVerb'
                else if word is 'beds'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else if word is 'bees'
                  mark word, 'pluralNoun'
                else if word is 'hips'
                  mark word, 'pluralNoun'
                else if word is 'dogs'
                  mark word, 'pluralNoun'
                else if word is 'begs'
                  mark word, 'presentVerb'
                else if word is 'bled'
                  mark word, 'pastVerb'
                else if word is 'died'
                  mark word, 'pastVerb'
                else if word is 'dies'
                  mark word, 'presentVerb'
                else if word is 'pops'
                  mark word, 'presentVerb'
                else if word is 'dips'
                  mark word, 'presentVerb'
                else if word is 'does'
                  mark word, 'presentVerb'
                else if word is 'beeps'
                  mark word, 'presentVerb'
                else if word is 'bides'
                  mark word, 'presentVerb'
                else if word is 'boils'
                  mark word, 'presentVerb'
                else if word is 'sped'
                  mark word, 'pastVerb'
                else if word is 'slid'
                  mark word, 'pastVerb'
                else if word is 'ills'
                  mark word, 'pluralNoun'
                else if word is 'dozed'
                  mark word, 'pastVerb'
                else if word is 'ebbed'
                  mark word, 'pastVerb'
                else if word is 'dozes'
                  mark word, 'presentVerb'
                else if word is 'hopes'
                  mark word, 'presentVerb'
                else if word is 'idled'
                  mark word, 'pastVerb'
                else if word is 'zipped'
                  mark word, 'pastVerb'
                  mark word, 'adjective'
                else if word is 'doses'
                  mark word, 'pluralNoun'
                else if word is 'solids'
                  mark word, 'pluralNoun'
                else if word is 'soloed'
                  mark word, 'pastVerb'
                else if word is 'slides'
                  mark word, 'presentVerb'
                else if word is 'sleeps'
                  mark word, 'presentVerb'
                else if word is 'glides'
                  mark word, 'presentVerb'
                else if word is 'sighed'
                  mark word, 'pastVerb'
                else if word is 'espieds'
                  mark word, 'presentVerb'
                else if word is 'espied'
                  mark word, 'pastVerb'
                else if word is 'elopes'
                  mark word, 'presentVerb'
                else if word is 'eloped'
                  mark word, 'pastVerb'
                else if word is 'dodges'
                  mark word, 'presentVerb'
                else if word is 'dodged'
                  mark word, 'pastVerb'
                else if word is 'helped'
                  mark word, 'pastVerb'
                else if word is 'heeded'
                  mark word, 'pastVerb'
                else if word is 'hissed'
                  mark word, 'pastVerb'
                else if word is 'hooded'
                  mark word, 'pastVerb'
                  mark word, 'adjective'
                else if word is 'popped'
                  mark word, 'pastVerb'
                else if word is 'seized'
                  mark word, 'pastVerb'
                else if word is 'pigs'
                  mark word, 'pluralNoun'
                else if word is 'pods'
                  mark word, 'pluralNoun'
                else if word is 'geese'
                  mark word, 'pluralNoun'
                else if word is 'globs'
                  mark word, 'pluralNoun'
                else if word is 'edges'
                  mark word, 'pluralNoun'
                  mark word, 'presentVerb'
                else
                  console.log word

                return
              definitions.forEach (definition)=>
                posType = _s.camelize(definition.meta.synsetType)
                if poss[posType]?
                  poss[posType].push word
                else 
                  poss[posType] = [word]



              # console.log JSON.stringify pos
              fs.writeFile  'common-calculator-words-by-pos.json', JSON.stringify(poss), (err)->
                if (err) 
                  throw err

              